INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('1', 'Sgt. Pepper\'s Lonely Hearts Club Band', 1967, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('2', 'Pet Sounds', 1966, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('3', 'The Shawshank Redemption', 1994, '2');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('4', 'The Godfather', 1972, '2');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('5', 'The Godfather: Part II', 1974, '2');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('6', 'Revolver', 1966, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('7', 'The Dark Knight', 2008, '2');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('8', 'Highway 61 Revisited', 1965, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('9', 'Schindlers List', 1993, '2');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('10', '12 Angry Men', 1957, '2');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('11', 'Pulp Fiction', 1994, '2');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('12', 'The Lord of the Rings: The Return of the King', 2003, '2');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('13', 'Rubber Soul', 1965, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('14', 'What\'s Going On', 1971, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('15', 'Exile on Main Street', 1972, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('16', 'The Good, the Bad and the Ugly', 1966, '2');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('17', 'London Calling', 1980, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('18', 'Blonde on Blonde', 1966, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('19', 'Fight Club', 1999, '2');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('20', 'The White Album', 1968, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('21', 'The Sun Sessions', 1976, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('22', 'Kind of Blue', 1959, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('23', 'The Velvet Underground', 1967, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('24', 'The LOTR: The Fellowship of the Ring', 2001, '2');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('25', 'Abbey Road', 1969, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('26', 'Are You Experienced', 1969, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('27', 'Blood on the Tracks', 1975, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('28', 'Nevermind', 1991, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('29', 'Born to Run', 1975, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('30', 'Astral Weeks', 1968, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('31', 'Thriller', 1982, '1');
INSERT INTO `media_shop`.`item` (`id`, `title`, `year`, `item_type_id`) VALUES ('32', 'The Great Twenty-Eight', 1982, '1');